// Centralized Data for 2026 Avurudu Nekath
const NEKATHS = [
  {
    id: "punya_start",
    title: "Punya Kaalaya Begins",
    time: "2026-04-14T03:08:00+05:30",
    icon: "moon",
    color: "White / Light",
    direction: "Any",
    desc: "Cease all work and engage in religious activities.",
    bg: "from-slate-900 via-indigo-900 to-purple-900",
  },
  {
    id: "dawn",
    title: "Dawn of the New Year",
    time: "2026-04-14T09:32:00+05:30",
    icon: "sun",
    color: "Green",
    direction: "South",
    desc: "The exact moment the sun enters Aries (Mesha).",
    bg: "from-orange-500 via-rose-500 to-purple-600",
  },
  {
    id: "cook",
    title: "Preparation of Meals",
    time: "2026-04-14T10:41:00+05:30",
    icon: "flame",
    color: "Red",
    direction: "South",
    desc: "Light the hearth and prepare milk rice (Kiribath).",
    bg: "from-red-600 via-orange-500 to-amber-500",
  },
  {
    id: "eat_work",
    title: "Work, Transactions & Meals",
    time: "2026-04-14T12:06:00+05:30",
    icon: "utensils",
    color: "Red",
    direction: "South",
    desc: "Commence work, perform Ganu-Denu, and partake in meals.",
    bg: "from-amber-400 via-orange-400 to-rose-400",
  },
  {
    id: "punya_end",
    title: "Punya Kaalaya Ends",
    time: "2026-04-14T15:56:00+05:30",
    icon: "check-circle-2",
    color: "Neutral",
    direction: "Any",
    desc: "End of the inauspicious transition period.",
    bg: "from-blue-500 via-cyan-500 to-teal-400",
  },
  {
    id: "oil",
    title: "Anointing with Oil",
    time: "2026-04-15T06:55:00+05:30",
    icon: "droplets",
    color: "Green",
    direction: "South",
    desc: "Apply herbal Nanu and oil for health and longevity.",
    bg: "from-emerald-500 via-teal-600 to-cyan-700",
  },
  {
    id: "work",
    title: "Leaving for Work",
    time: "2026-04-20T06:27:00+05:30",
    icon: "briefcase",
    color: "White",
    direction: "South",
    desc: "Set off to resume professional duties and businesses.",
    bg: "from-sky-400 via-blue-500 to-indigo-600",
  },
  {
    id: "plant",
    title: "Planting Tree Saplings",
    time: "2026-04-23T09:01:00+05:30",
    icon: "leaf",
    color: "Gold / Green",
    direction: "North",
    desc: "Plant a sapling for environmental prosperity.",
    bg: "from-green-500 via-emerald-600 to-teal-700",
  },
];
